version: "3.3"
services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./static:/data
    restart: unless-stopped
    networks:
      - default
  
  redis:
    container_name: Redis
    image: redis/redis-stack:latest
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ~/.docker/redis:/data



  app:
    container_name: App
    build: .
    volumes:
      - .:/app

  nginx:
    container_name: Nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - app


networks:
  default:
    driver: bridge

volumes:
  minio_data:
    driver: local